apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-pods
  namespace: default
spec:
  schedule: "0 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: delete-pods-sa
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl get pods --all-namespaces --field-selector=status.phase!=Running,status.phase!=Pending -o jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | while read  namespace name; do
              kubectl delete pod $name -n $namespace;
              done
          restartPolicy: Never
