apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-pods-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: delete-pods-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: delete-pods-clusterrole
  apiGroup: rbac.authorization.k8s.io
